url: "https://wowjs.uk"

# Build settings
markdown: kramdown
highlighter: rouge
relative_permalinks: false
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems:
  - jekyll-paginate
  - jekyll-feed
